#!/usr/bin/env node
// Render infra/grant-request.md from a deployment's outputs (ADR-0012, decision D11).
//
// The use case's identities need roles on SHARED resources (registry, Foundry, AI Search) and
// on its own storage account; the deployment identity (Contributor) cannot assign roles, so the
// request goes to the cloud team as a document. This script never calls Azure.
//
//   node scripts/grant-request.mjs <deployment.json> [--env dev] [--out infra/grant-request.md]
//
// <deployment.json> is either the artifact uploaded by .github/workflows/infra.yml
// (`az deployment group create --output json`) or the output of
// `az deployment group show -g <rg> -n <name> --output json`, or just its `properties.outputs`.
import { readFileSync, writeFileSync } from 'node:fs';

const args = process.argv.slice(2);
const file = args.find((a) => !a.startsWith('--'));
const opt = (name, fallback) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
};
if (!file) {
  console.error(
    'usage: node scripts/grant-request.mjs <deployment.json> [--env dev] [--out infra/grant-request.md]',
  );
  process.exit(2);
}

const raw = JSON.parse(readFileSync(file, 'utf8'));
const outputs = raw?.properties?.outputs ?? raw?.outputs ?? raw;
const grants = outputs?.grantRequest?.value ?? outputs?.grantRequest;
if (!Array.isArray(grants) || grants.length === 0) {
  console.error(
    'no `grantRequest` output found — was main.bicep deployed with its outputs intact?',
  );
  process.exit(1);
}

const env = opt('env', process.env.TARGET_ENV ?? 'dev');
const out = opt('out', 'infra/grant-request.md');
const date = new Date().toISOString().slice(0, 10);

const byIdentity = new Map();
for (const g of grants) {
  if (!byIdentity.has(g.identity))
    byIdentity.set(g.identity, { principalId: g.principalId, rows: [] });
  byIdentity.get(g.identity).rows.push(g);
}

const lines = [
  `# Role grant request — \`${env}\` (${date})`,
  '',
  '> Generated by `scripts/grant-request.mjs` from the deployment outputs. This use case deploys',
  '> only its own resources (ADR-0012); the roles below are on **shared, cloud-team-owned**',
  '> resources (and on our own storage account, because the deployment identity cannot assign',
  '> roles). Please grant them to the managed identities listed. Nothing here is a secret.',
  '',
  '| Identity | Principal ID | Role | Scope | Why |',
  '| --- | --- | --- | --- | --- |',
];
for (const [identity, { rows }] of byIdentity) {
  for (const r of rows)
    lines.push(
      `| \`${identity}\` | \`${r.principalId}\` | ${r.role} | \`${r.scope}\` | ${r.why} |`,
    );
}
lines.push('', '## Equivalent CLI (for the cloud team)', '', '```bash');
for (const r of grants) {
  lines.push(
    `az role assignment create --assignee-object-id ${r.principalId} --assignee-principal-type ServicePrincipal --role "${r.role}" --scope "${r.scope}"`,
  );
}
lines.push(
  '```',
  '',
  'After granting: set `deployContainerApps = true` in `infra/main.' +
    env +
    '.bicepparam` and deploy again.',
  '',
);

writeFileSync(out, lines.join('\n'), 'utf8');
console.log(`${out}: ${grants.length} grants for ${byIdentity.size} identities (${env})`);
