"""Export the api's OpenAPI document — the contract the web layer codes against.

    uv run python -m app.openapi_export                # → ../../docs/reference/openapi.json
    uv run python -m app.openapi_export path/to/out.json

The committed ``docs/reference/openapi.json`` is regenerated by ``make openapi`` (which also
regenerates ``apps/web/src/lib/api-types.ts`` with openapi-typescript) and CI fails when it is
stale, so a backend change to the ``/v1`` surface is always visible to the frontend developer
as a diff — and the mocks they type against it stay honest.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

DEFAULT_OUTPUT = Path(__file__).resolve().parents[3] / "docs" / "reference" / "openapi.json"


def render_openapi() -> str:
    """The OpenAPI document as deterministic, pretty-printed JSON (stable diffs)."""
    from app.main import app

    return json.dumps(app.openapi(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def export_openapi(output: Path = DEFAULT_OUTPUT) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_openapi(), encoding="utf-8")
    return output


def main(argv: list[str] | None = None) -> None:
    args = list(sys.argv[1:] if argv is None else argv)
    output = Path(args[0]) if args else DEFAULT_OUTPUT
    written = export_openapi(output)
    print(f"wrote {written}")


if __name__ == "__main__":
    main()
